server:
  port: 9002
spring:
  application:
    name: titles-service
  datasource:
    url: jdbc:postgresql://localhost:5434/titles
    username: titles
    password: titles
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
      enabled: true
      locations: classpath:db/migration