federation_version: 2
subgraphs:
  users:
    routing_url: http://localhost:9001/graphql
    schema:
      file: users/schema.graphql
  titles:
    routing_url: http://localhost:9002/graphql
    schema:
      file: titles/schema.graphql
  ratings:
    routing_url: http://localhost:9003/graphql
    schema:
      file: ratings/schema.graphql