server:
  port: 9003
spring:
  application:
    name: ratings-service
  datasource:
    url: jdbc:postgresql://localhost:5435/ratings
    username: ratings
    password: ratings

  jpa:
    hibernate:
    ddl-auto: create
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
#users:
#  url: http://localhost:9001/graphql