server:
  port: 9001
spring:
 application:
  name: user-service
 datasource:
   url: jdbc:postgresql://localhost:5433/users
   username: users
   password: users
   jpa:
     hibernate:
       ddl-auto: validate
     show-sql: true
     database-platform: org.hibernate.dialect.PostgreSQLDialect
   flyway:
     enabled: true
     locations: classpath:db/migration